name: Deploy to TRMNL

on:
  push:
    branches: [main]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install trmnlp
        run: gem install trmnl_preview
      - name: Push to TRMNL
        env:
          TRMNL_API_KEY: ${{ secrets.TRMNL_API_KEY }}
        run: trmnlp push --force --id 9f7971b0-25f1-4d75-b28f-64615607f2e3
